spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nakama?useUnicode=true&characterEncoding=utf8
    name:
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show_sql: false
  thymeleaf:
    cache: false
security:
  basic:
    enabled: false
server:
  port: 8080
  tomcat:
    access_log_enabled: true
    basedir: build/tomcat