spring:
  data:
    cassandra:
      keyspace-name: nakama
      schema-action: recreate_drop_unused
      contact-points: localhost
      port: 9042
      cluster-name: Test Cluster

logging:
  level:
    org:
      springframework:
        security: debug
